tact-lang/tact-docs

pages/tools/vs.mdx
This PR consist of: 
- guide to installing vs code extension
- guide to turning format on save for better developer experience
=> feat: vs code extension docs

pages/language/ref/_meta.json, pages/language/ref/message-modes.mdx
i thought it would nice to have a cheat sheet of message modes in tact with their description.
=> feat: message modes documentation

pages/language/guides/external.mdx, pages/language/guides/statements.mdx
adding the content and clarify each Loop statement
=> Update page Loop

pages/language/guides/receive.mdx
Corrected a spelling mistake in the word "receive".
=> fix: corrected a typo in the documentation

pages/language/guides/lifecycle.mdx
there was two from,  I removed one
=> omit from word

pages/language/ref/math.mdx
=> Fix checkDataSignature's signature

pages/language/ref/random.mdx
=> fix: random() uses semi-open interal

theme.config.jsx
=> fix: edit this page links

scripts/proposals-generate.js
=> fix[CI]: Updated `scripts/proposals-generate.js`

pages/language/ref/exit-codes.mdx
Hi @reveloper @anton-trunov @novusnota 
I've modified the docs as @reveloper said. Now, it's much better.
And made a PR as @novusnota said.
Thanks for it!
=> exit codes added

pages/book/contracts.mdx, pages/book/message-mode.mdx, pages/book/send.mdx, pages/cookbook/index.mdx
=> fix: + to | for `mode` of `SendParameters` Struct

pages/index.mdx
=> chore: typo on the main page

pages/book/optionals.mdx
=> chore: typo

pages/book/maps.mdx
=> feat: .del() method for maps

pages/book/maps.mdx, pages/book/statements.mdx
Closes #159
P.S.: 4 commits because I've forgot to do the rebase instead of merge. But the end result (changes) is fine
=> feat: `foreach` statement

grammars/grammar-tact.json, next.config.js
* New grammar, fresh from Sublime Text package
* And a new theme, which better suits it and the docs: One Dark
Closes #229
=> feat: new grammar

pages/book/config.mdx, pages/book/expressions.mdx, pages/book/integers.mdx, pages/book/operators.mdx, pages/book/structs-and-messages.mdx, pages/ref/core-advanced.mdx, pages/ref/core-base.mdx, pages/ref/core-common.mdx, pages/ref/core-math.mdx, pages/ref/core-random.mdx, pages/ref/core-strings.mdx
Major whoopsie of mine that went unnoticed. Until now, that is :)
I'll definitely take a look at #65 soon to prevent similar cases in the future.
Closes #243
=> fix: broken links

.github/workflows/nextjs.yml, .github/workflows/test-build-nextjs.yml, cspell.json, package.json, pages/book/_meta.js, pages/book/constants.mdx, pages/book/contracts.mdx, pages/book/index.mdx, pages/book/operators.mdx, pages/book/statements.mdx, pages/book/structs-and-messages.mdx, pages/cookbook/data-structures.mdx, pages/ref/core-base.mdx, pages/ref/core-cells.mdx, pages/ref/core-common.mdx, pages/ref/core-debug.mdx, pages/ref/evolution/overview.mdx, pages/ref/stdlib-config.mdx, yarn.lock
=> fix: typos + add spellchecking to CI

pages/ref/core-cells.mdx
=> feat: removed return value of `Slice.skipBits()`

cspell.json, pages/book/config.mdx
=> feat: `fullWithDecompilation`

pages/book/debug.mdx, pages/cookbook/misc.mdx, pages/ref/core-debug.mdx
=> chore: nativeThrowWhen → nativeThrowIf

grammars/grammar-tact.json
=> feat: update TextMate grammar for Tact 1.4.0

pages/ref/core-cells.mdx
=> feat: add `Slice.loadBool` function

pages/book/structs-and-messages.mdx, pages/ref/core-cells.mdx
And a correction about the field ordering.
Towards #255.
=> feat: Optional final `;` in field declarations of Structs and Messages

pages/book/statements.mdx
=> feat: Iteration over maps in contract storage and struct/message fields

pages/book/statements.mdx
Compiler PR: https://github.com/tact-lang/tact/pull/479
=> fix: foreach error messages

pages/book/statements.mdx
=> feat: Local type inference for `let` statements

pages/book/operators.mdx
=> fix: corrected augmented assignment operations

pages/book/debug.mdx, pages/book/integers.mdx, pages/book/send.mdx, pages/ref/core-advanced.mdx, pages/ref/core-base.mdx, pages/ref/core-cells.mdx, pages/ref/core-common.mdx, pages/ref/core-comptime.mdx, pages/ref/core-strings.mdx
And also specify all message sending functions on book/send page
Closes #292
=> feat: clarity `myBalance()`, nanoToncoin format

cspell.json, pages/book/_meta.js, pages/book/debug.mdx, pages/book/masterchain.mdx, pages/ref/core-debug.mdx
=> feat: update masterchain page

pages/book/config.mdx, pages/book/contracts.mdx
=> feat: add new configuration options to `book/config`

pages/book/integers.mdx, pages/ref/core-cells.mdx
=> feat/fix: update description of coins serialization format

pages/book/structs-and-messages.mdx
=> fix/chore: paraphrased description of optional fields in structs

.gitignore, pages/cookbook/access.mdx
https://github.com/tact-lang/tact-docs/issues/316
=> Add examples for requireOwner()

pages/ecosystem/tools/typescript.mdx
=> fix/feat: rephrased ecosystem/tools/typescript and updated links

pages/book/send.mdx, pages/ref/core-advanced.mdx, pages/ref/core-base.mdx, pages/ref/core-common.mdx
Explains outbound message processing, compute vs. action phases and gives an example of a somewhat complicated situation described in #303.
Closes #309 
Closes #303
P.S.: Messed up commit history on this one, whoops!
=> feat: clarify outbound messages

pages/book/contracts.mdx
=> fix: correct formatting in book/contracts

cspell.json, pages/book/contracts.mdx, pages/ref/core-base.mdx
=> feat: describe inheritance via `with` keyword and BaseTrait

pages/book/debug.mdx
=> feat: how-to parse emitted message bodies using TypeScript wrappers

pages/ecosystem/tools/misti.mdx, pages/ecosystem/tools/overview.mdx
=> Add a page on Misti static analyzer

pages/book/statements.mdx
=> fix: specify appropriate map method

pages/book/maps.mdx
=> fix: correct map values type (from String to Int)

pages/index.mdx
=> feat: add project creation command with Bun

grammars/grammar-tact.json
=> feat: update TextMate grammar for Tact 1.5.0
