pages/language/guides/functions.mdx, pages/start/first.mdx
Fixed some minor typos in the example snippets:
e.g.
```
fun pow(a: Int, c: Int): Int {
let res: Int = a;
repeat(c) {
res = res * a;
}
return res;
}
```
Should be 
`  let res: Int = 1;`
=> Fixed typos on 'functions' page

.github/workflows/test-build-nextjs.yml, next.config.js, package.json, theme.config.jsx
The main issue is still the same — Next.js (the underlying thing our doc theme uses) is very tough then it comes to combining i18n with static export as we do it now. That was the primary reason it took me whole 2 days to make it semi-right, but this time the fix is going to be very tough, [because of this incompatibility](https://nextjs.org/docs/messages/export-no-i18n). I'll try to look into it more, but at the moment I have a bold suggestion to move the docs to https://starlight.astro.build, as it's way easier to manage (I've tried already).
There's [next-intl](https://github.com/amannn/next-intl) package, which may be nice with our setup, but will still require a ton of bike-shredding. In any case, I'll figure out a solution for keeping i18n and static exports.
=> fix[CI]: Added a new workflow and temporarily disabled i18n

next.config.js, pages/book/index.mdx, pages/ecosystem/index.mdx, pages/ecosystem/tools/_meta.js, pages/ecosystem/tools/overview.mdx, pages/index.mdx, pages/language/index.mdx, pages/language/ref/_meta.js, pages/language/ref/exit-codes.mdx
Also, added a stub page for `/exit-codes` for @alirezatabatabaeian to populate.
Closes #84
=> quickfix: broken links

pages/book/_meta.js, pages/book/import.mdx, pages/language/libs/overview.mdx
With the updated description for the import statement, and most contents brought over from the Language→Libs→Overview. This is due to the fact that Language→Libs update happened before the new structure was fully thought of and introduced. This PR resolves that issue and places information where it's needed most.
Closes #63
=> feat/fix: Added a page "Importing code" to the Book

.github/workflows/test-build-nextjs.yml, pages/language/ref/advanced.mdx
Fixed the formatting of `nativeReserve` and the rest of the page.\
Also allowed multiple parallel test builds (but not deploy ones).
Related to https://github.com/tact-lang/tact/issues/172
=> fix: Language->Ref->Advanced

pages/book/_meta.js, pages/book/composite-types.mdx, pages/book/integers.mdx, pages/book/types.mdx, scripts/redirects-generate.js
Adds a new page to the Book — "Integers", which describes integer literals, serialization as `tl-b` types and more.
Closes #60
Closes #61
The page makes couple of references to the new page added there: https://github.com/tact-lang/tact-docs/pull/95
=> feat: Integer update

.github/temp-archive/learn/wallet/wallet-2.mdx, pages/book/cookbook.mdx, pages/book/exit-codes.mdx, pages/book/functions.mdx, pages/book/types.mdx, pages/language/libs/dns.mdx
This is a follow-up PR on #118, using more augmented assignment operators in Tact docs
=> fix: use `+=`, `*=`, `-=` operators

.github/workflows/nextjs.yml, .github/workflows/test-build-nextjs.yml, next.config.js, package.json, pages/_app.mdx
Small (1-2 line) fixes of Nextra/Next.js suggestions
* `_app.tsx` -> `_app.mdx`.
Closes #120
* `output: 'export'` in `next.config.js`.
Closes #123
* max fetch depth for CI to correct "latest modified" times.
Closes #121
=> chore: Nextra/Next.js suggestions

pages/book/_meta.js, pages/book/cookbook.mdx, pages/book/expressions.mdx, pages/book/func.mdx, pages/book/integers.mdx, pages/book/maps.mdx, pages/book/operators.mdx, pages/book/optionals.mdx, pages/book/structs-and-messages.mdx, pages/book/types.mdx, scripts/redirects-generate.js
* "Structs and Messages", "Maps" and "Optionals" -- now became standalone pages
* Corrected all the links throughout the Book
* Re-organized `/book/types` to reference all the pages
* Added a redirect from `/book/composite-types` to `/book/types#composite-types`
Closes #134
=> chore: Split `composite-types` into standalone pages

pages/book/cookbook.mdx, pages/book/message-mode.mdx, pages/book/send.mdx
* Clean-up in `/book/message-mode`
* Re-write of `/book/send`
* More examples on sending messages in `/book/cookbook`
Closes #127
=> fix/feat: More information on sending messages

pages/_meta.js, pages/book/_meta.js, pages/book/index.mdx, pages/cookbook/_meta.js, pages/cookbook/index.mdx, pages/index.mdx, scripts/redirects-generate.js, theme.config.jsx
* Changed descriptions on the main page
* Added a redirect `/book/cookbook` -> `/cookbook`
As a bonus, added an `Scroll to top` button to all terms of contents on all pages.
Closes #144.
=> chore: Moved Cookbook into its own section

package.json, pages/book/contracts.mdx, pages/book/maps.mdx, pages/cookbook/index.mdx
Added or refined:
* `.get()`
* `.set()`
* `.asCell()`
* Deletion of individual or all entries
* Iteration over maps
* Mention of issues with large maps and how to mitigate them:
1. With upper-bounds
2. Or with contract sharding
And everything with examples of Tact code, except for contract sharding, which will be added later as per #155.
As a bonus, added two neat examples of using maps as arrays to Cookbook (with handy comments): one from @howardpen9 :fire:, another from tact-by-example and @talkol :fire:
Closes #135
Closes #133
=> feat: Maps page update

pages/book/operators.mdx
```
let two: Int = 2;
two / 2; // 1
two / 1; // 0
-1 / 5;  // -1
```
`two / 1; // 0`
This is the integer division of 2 by 1, which is 2. However, it seems the comment claims the result to be 0, which is incorrect. The correct result is indeed 2.
=> Correct the result of `two / 1` in operators.mdx

pages/book/operators.mdx
```
let two: Int = 2;
two % 2; // 0
two % 1; // 1
```
The expression `two % 1` should yield 0 instead of 1. The comment here is incorrect. I believe it should be `1 % two`.
=> fix(book/operators)-Modulo

.github/workflows/nextjs.yml
See: #167
I'm almost done with #143 and I thought that it would be nice to start adding new features of Tact 1.3.0 right away.
Because there's no versioning of the docs yet, I suggest we temporarily move to a `workflow_dispatch` mode of updates (manual button press in the Github's Actions UI) until Tact 1.3.0 or #167 releases.
=> chore[ci]: Temporarily disable on-push deploy to start adding new Tact features

pages/book/guides/getting-started/deploy.mdx
See https://github.com/tact-lang/tact-docs/issues/171
Fix #171
=> Fix ton core import in /pages/book/guides/getting-started/deploy.mdx

pages/book/functions.mdx
The page will be modified as per #131
Closes #196.
=> fix: just the small bug

pages/book/expressions.mdx
=> feat: add string escape sequences

pages/book/maps.mdx
And minor adjustments to the headers and ToC.
Closes #188
=> feat: `.isEmpty()` method for maps

pages/book/message-mode.mdx, pages/book/operators.mdx
* All precedences match Tact 1.3.0
* Added bitwise XOR operator `^`
* Fixed minor typos and corrected some descriptions
* Added a table of operators in decreasing order of their precedences
Note, that the only link leading to Language section now has a proper link to the Reference section. This is intentional, as the Lang->Ref rename is almost there :)
Closes #192 (new operator precedence + a table) — this is the main issue target of this PR
Closes #202 (small error)
Closes #181 (small note)
Closes #178 (small correction)
=> feat: Update of the Book→Operators page

pages/book/structs-and-messages.mdx
* Instantiation description
* Trailing comma
* Field punning
* `.toCell()` extension function
* Cross-link to Expressions#instantiation
Note, that `.toCell()` adds links to non-existent yet Reference section, but those links will be eventually correct once #206 is completed (quite soon!).
Closes #210 (field punning) — main target of this PR
Closes #212 (`.toCell()` function)
Closes #154 (just a reference link)
=> feat: small Structs and Messages update

pages/index.mdx
Closes #231
Alternatively, we may just send `null` in `self.notify()`, but that would be less descriptive, so I went with the same approach used in `@stdlib/deploy`. And so it "notifies" the sender about the `AddOk` message, alongside with returning remaining value from the obtained message (implicitly)
UPD: Decided to just use `self.notify("Cashback".asComment());`
=> feat: send excessive funds from receiver function back to the sender

pages/book/bounced.mdx, pages/book/types.mdx
Closes #186
Specified a `bounced<T>` type constructor on the `/book/types` page and made a bunch of small edits on the `/book/bounced` page.
=> feat: bounced type constructor description

pages/book/bounced.mdx, pages/book/contracts.mdx, pages/book/maps.mdx, pages/book/message-mode.mdx, pages/book/operators.mdx, pages/book/optionals.mdx, pages/book/types.mdx, pages/cookbook/data-structures.mdx, pages/ref/core-advanced.mdx, pages/ref/core-base.mdx, pages/ref/standard-libraries.mdx, pages/ref/stdlib-ownable.mdx, pages/ref/stdlib-stoppable.mdx
* Capitalized type letters in `map<k, v>` to be `map<K, V>`
* Added `()` after any reference to a function name
* Prefixed things in `core-base.mdx` with `self.`
* Various smaller corrections, like removal of highlighting for "bitwise OR" literally (not to be confused with highlighting of the operator `|`)
Closes #195
=> chore: highlighting-related housekeeping

grammars/grammar-tact.json
Description of changes:
https://github.com/tact-lang/tact-sublime/commit/ffc2d9a73a95c85815acfdd3a221c3d48a51a979
In general, docs are already looking better than ever, but I wanted to go a little bit further and added couple of smaller enhancements :)
=> chore: final enhancements for the Tact's grammar

pages/book/config.mdx, pages/book/expressions.mdx, pages/book/integers.mdx, pages/book/operators.mdx, pages/book/structs-and-messages.mdx, pages/ref/core-advanced.mdx, pages/ref/core-base.mdx, pages/ref/core-common.mdx, pages/ref/core-math.mdx, pages/ref/core-random.mdx, pages/ref/core-strings.mdx
=> feat: describe how to obtain config params

pages/book/statements.mdx
Based on this conversation in the Tact tg group:
=> Update statements.mdx with warning over iterating members of a struct

pages/cookbook/data-structures.mdx
=> chore: corrected leftovers of lowercase types in map constructors

pages/book/functions.mdx, pages/book/lifecycle.mdx, pages/book/masterchain.mdx, pages/book/upgrades.mdx
Based on TON FunC document the structure of the `FunC` language name should have capital `F` and `C`, and there is a possibility of misunderstanding between the `FunC language` and `fun` expression or function synonym.
That was what happened to me personally
=> typo: FunC language name

pages/book/statements.mdx
=> feat: Optional `;` in the last statement in the block

pages/book/structs-and-messages.mdx, pages/cookbook/type-conversion.mdx, pages/ref/core-cells.mdx, scripts/redirects-generate.js
=> feat: `.fromCell()` and `.fromSlice()` functions

pages/book/lifecycle.mdx
Looking at the current config values at https://tonscan.org/config#20, the maximum gas limit for a single transaction is 10 TON.
=> Update the maximum gas limit per transaction to 10 TON

pages/book/_meta.js, pages/index.mdx
...and also slightly updated the index page to encourage people to search and seek answers themselves first, before they go in Tact chats. That won't work on everyone, of course, but it's important to at least mention that we have the search box :)
Closes #328
=> chore: moved exit codes page in "Fundamentals of Tact"

pages/cookbook/data-structures.mdx
=> fix: make code in Cookbook compile

pages/book/contracts.mdx, pages/book/receive.mdx
Closes #285
I'll remove duplication when resolving #131: receive(), bounced() and external() will have full descriptions on their individual pages, and other places such as functions page and contracts page would briefly show how they look and provide links to "Read more" for all the details. That's because receivers are less of a syntax construct and more of a bigger conceptual thing tightly related to the message and actor-based model of TON Blockchain.
=> feat: underscores as parameter names in receivers

pages/book/cells.mdx, pages/ref/core-strings.mdx
=> feat: standard representation of a cell and a slight re-order of things

pages/book/statements.mdx
=> fix: clarify bounds of values in `repeat` statement

pages/book/cells.mdx
=> feat: explanation of `remaining` serialization format

pages/book/cells.mdx
And that writing `map<T, Cell as remaining>` now causes a compilation error.
Closes #353
=> feat: clarify that `remaining` is only allowed for the last field

pages/book/debug.mdx
And provide helpful set of topics to quickly jump to right at the beginning. Thought that leaving just a couple words in "General approach" might still be helpful, so didn't remove that section completely.
Closes #385
=> feat: condense the `debug#approach` section to the minimum
